### PR TITLE
Aptfield removed

### PR DESCRIPTION
**Pull request by AzukaUgbekile**
Removed the Aptfield

### CODE REVIEW

**Review by BorisLaboratory — CHANGES_REQUESTED** [review]
I am not sure if you considered acceptance criterial #2 - ie Street field should span the entire with of the component. My SUGGESTION: on line 159 experiment changing grid to for example : Grid xs={12} item, without the sm={9} .Every other thing looks good. Good work

**Review by dellydel — APPROVED** [review]
Perfect

**Comment by AzukaUgbekile** [comment]
Honestly, I didn't see that.

**Comment by AzukaUgbekile** [comment]
Change made

**Review by dellydel — APPROVED** [review]

**Comment by AzukaUgbekile** [comment]
Thank you.

I can't merge to main

**Review by dellydel — APPROVED** [review]

**Pull request merged**
